# clustering_edgecases_test.py
# Run: python3 clustering_edgecases_test.py

from pprint import pprint
import numpy as np
from sklearn.cluster import DBSCAN
# ---- import your function ----
# If TargetPoseEst.py is alongside this file:
def merge_estimations(target_pose_dict, eps=0.15, min_samples=2):
    """
    function:
        merge estimations of the same target
    input:
        target_pose_dict: dict, generated by estimate_pose
    output:
        target_est: dict, target pose estimations after merging

    need to add outter bound of 2.7m
    """
    target_est = {}

    ######### Replace with your codes #########
    # TODO: replace it with a solution to merge the multiple occurrences of the same class type (e.g., by a distance threshold)
    # Convert dict to list of (class, x, y)
    detections = []
    for key, pose in target_pose_dict.items():
        target_type = key.split('_')[0]
        detections.append((target_type, pose['x'], pose['y']))

    # Process per class
    for target_type in set([d[0] for d in detections]):
        coords = np.array([[d[1], d[2]] for d in detections if d[0] == target_type])

        if len(coords) == 0:
            continue

        clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(coords)

        cluster_id = 0
        for cid in set(clustering.labels_):
            if cid == -1:  # noise
                continue
            cluster_points = coords[clustering.labels_ == cid]
            x_mean, y_mean = cluster_points.mean(axis=0)
            target_est[f"{target_type}_{cluster_id}"] = {"x": float(x_mean),
                                                         "y": float(y_mean)}
            cluster_id += 1
    #########
   
    return target_est

def run_case(name, target_pose_dict, eps=0.15, min_samples=2):
    print(f"\n=== {name} | eps={eps}, min_samples={min_samples} ===")
    merged = merge_estimations(target_pose_dict, eps=eps, min_samples=min_samples)
    pprint(merged)

# 1) Basic: two clear orange clusters + one clear pear cluster + one outlier
case_basic = {
    "orange_0": {"x": 1.00, "y": 1.00},
    "orange_1": {"x": 10.06, "y": 0.96},
    "orange_2": {"x": 0.96, "y": 1.10},

    "orange_3": {"x": 2.50, "y": 2.50},
    "orange_4": {"x": 2.64, "y": 2.46},

    "pear_0": {"x": 0.50, "y": -0.20},
    "pear_1": {"x": 0.62, "y": -0.18},
    "pear_2": {"x": 3.10, "y": 3.00},  # outlier (noise)
}

# 2) Near-threshold: points right around eps (to test sensitivity)
#    With eps=0.15, (0,0)↔(0.149,0.0) should cluster; (0,0)↔(0.151,0.0) should not.
case_near_threshold = {
    "tomato_0": {"x": 0.00, "y": 0.00},
    "tomato_1": {"x": 0.149, "y": 0.00},
    "tomato_2": {"x": 0.151, "y": 0.00},  # just outside if eps=0.15
}

# 3) Singletons: only one detection per class → should be noise if min_samples=2
case_singletons = {
    "pumpkin_0": {"x": 1.2, "y": -0.3},
    "garlic_0":  {"x": 0.2, "y":  0.7},
}

# 4) Mixed tight clusters for multiple classes, some very close (< eps) and some spaced out
case_mixed = {
    # capsicum cluster A
    "capsicum_0": {"x": -0.5, "y":  0.5},
    "capsicum_1": {"x": -0.45,"y":  0.47},
    "capsicum_2": {"x": -0.51,"y":  0.55},
    # capsicum cluster B
    "capsicum_3": {"x":  0.8, "y": -0.9},
    "capsicum_4": {"x":  0.95,"y": -0.88},

    # potato: one tight pair + one isolated outlier
    "potato_0": {"x": -1.0, "y":  1.0},
    "potato_1": {"x": -1.08,"y":  1.02},
    "potato_2": {"x":  0.20,"y":  1.50},  # outlier/noise

    # orange: collinear but spaced within eps
    "orange_0": {"x": 0.0,  "y": 0.0},
    "orange_1": {"x": 0.07, "y": 0.0},
    "orange_2": {"x": 0.14, "y": 0.0},
}

# 5) Border/negative coords: positions near arena edges / negative values
case_borders = {
    "lemon_0": {"x": -1.2, "y": -1.2},
    "lemon_1": {"x": -1.25,"y": -1.15},
    "lemon_2": {"x": +1.20,"y": +1.20},  # clearly separate cluster if min_samples allows
    "lemon_3": {"x": +1.34,"y": +1.19},
}

# 6) Dense cluster with one far false positive (tests noise rejection)
case_dense_with_false = {
    "garlic_0": {"x": 0.3, "y": 0.3},
    "garlic_1": {"x": 0.31,"y": 0.29},
    "garlic_2": {"x": 0.29,"y": 0.32},
    "garlic_3": {"x": 0.28,"y": 0.31},
    "garlic_4": {"x": 1.2, "y": -0.8},  # noise
}

# 7) Tight cluster but min_samples=3 (to show stricter setting)
case_min_samples_3 = {
    "pumpkin_0": {"x":  0.0, "y": 0.0},
    "pumpkin_1": {"x":  0.1, "y": 0.0},
    # With min_samples=3, this pair is NOT enough; add a third close point:
    "pumpkin_2": {"x":  0.05,"y": 0.03},

    # Another class with only two points → won't appear when min_samples=3
    "pear_0": {"x": -0.2, "y": 0.4},
    "pear_1": {"x": -0.25,"y": 0.45},
}

# 8) Overlapping multi-class geometry (same region, different labels)
#    Should not cross-cluster across classes.
case_overlapping_classes = {
    "orange_0":  {"x": 0.0, "y": 0.0},
    "orange_1":  {"x": 0.05,"y": 0.02},
    "tomato_0":  {"x": 0.02,"y": 0.01},
    "tomato_1":  {"x": 0.07,"y":-0.01},
}

if __name__ == "__main__":
    # Default eps ~ 0.15 m per arena rule, min_samples=2
    run_case("BASIC", case_basic, eps=0.2, min_samples=2)
    run_case("NEAR_THRESHOLD", case_near_threshold, eps=0.15, min_samples=2)
    run_case("SINGLETONS", case_singletons, eps=0.15, min_samples=2)
    run_case("MIXED", case_mixed, eps=0.15, min_samples=2)
    run_case("BORDERS", case_borders, eps=0.15, min_samples=2)
    run_case("DENSE_WITH_FALSE", case_dense_with_false, eps=0.15, min_samples=2)

    # Show impact of min_samples=3 (stricter)
    run_case("MIN_SAMPLES_3", case_min_samples_3, eps=0.15, min_samples=3)

    # Show that different labels in same region don’t mix
    run_case("OVERLAPPING_CLASSES", case_overlapping_classes, eps=0.12, min_samples=2)
