# estimate the pose of target objects detected
import numpy as np
import json
import os
import ast
import cv2
# plotting (added for visualising detections)
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
from YOLO.detector import Detector
from sklearn.cluster import DBSCAN

# Default to None
yolo = None

# list of target fruits and vegs types
# Make sure the names are the same as the ones used in your YOLO model
TARGET_TYPES = ['orange', 'lemon', 'lime', 'tomato', 'capsicum', 'potato', 'pumpkin', 'garlic']
ARENA_SIZE  = 2.7
ARENA_BOUND = ARENA_SIZE / 2.0  # ±1.35 m

def estimate_pose(camera_matrix, obj_info, robot_pose):
    """
    function:
        estimate the pose of a target based on size and location of its bounding box and the corresponding robot pose
    input:
        camera_matrix: list, the intrinsic matrix computed from camera calibration (read from 'param/intrinsic.txt')
            |f_x, s,   c_x|
            |0,   f_y, c_y|
            |0,   0,   1  |
            (f_x, f_y): focal length in pixels
            (c_x, c_y): optical centre in pixels
            s: skew coefficient (should be 0 for PenguinPi)
        obj_info: list, an individual bounding box in an image (generated by get_bounding_box, [label,[x,y,width,height]])
        robot_pose: list, pose of robot corresponding to the image (read from 'lab_output/images.txt', [x,y,theta])
    output:
        target_pose: dict, prediction of target pose
    """
    # read in camera matrix (from camera calibration results)
    focal_length = camera_matrix[0][0]

    # there are 8 possible types of fruits and vegs
    ######### Replace with your codes #########
    # TODO: measure actual sizes of targets [width, depth, height] and update the dictionary of true target dimensions
    target_dimensions_dict = {'orange': [0.07,0.07,0.073], 'lemon': [0.078,0.053,0.05], 
                              'pear': [0.076,0.074,0.11], 'tomato': [0.065,0.065,0.06], 
                              'capsicum': [0.076,0.074,0.09], 'potato': [0.095,0.065,0.07], 
                              'pumpkin': [0.08,0.08,0.08], 'garlic': [0.065,0.06,0.07]}  # 'lime': [0.074,0.052,0.05]
    #########

    # estimate target pose using bounding box and robot pose
    target_class = obj_info[0]     # get predicted target label of the box
    target_box = obj_info[1]       # get bounding box measures: [x,y,width,height]
    true_height = target_dimensions_dict[target_class][2]   # look up true height of by class label

    # compute pose of the target based on bounding box info, true object height, and robot's pose
    pixel_height = target_box[3]
    pixel_center = target_box[0]
    distance = true_height/pixel_height * focal_length  # estimated distance between the robot and the centre of the image plane based on height
    # training image size 320x240p
    image_width = 320 # change this if your training image is in a different size (check details of pred_0.png taken by your robot)
    x_shift = image_width/2 - pixel_center              # x distance between bounding box centre and centreline in camera view
    theta = np.arctan(x_shift/focal_length)     # angle of object relative to the robot
    ang = theta + robot_pose[2]     # angle of object in the world frame
    
   # relative object location
    distance_obj = distance/np.cos(theta) # relative distance between robot and object
    x_relative = distance_obj * np.cos(theta) # relative x pose
    y_relative = distance_obj * np.sin(theta) # relative y pose
    relative_pose = {'x': x_relative, 'y': y_relative}
    #print(f'relative_pose: {relative_pose}')

    # location of object in the world frame using rotation matrix
    delta_x_world = x_relative * np.cos(robot_pose[2]) - y_relative * np.sin(robot_pose[2])
    delta_y_world = x_relative * np.sin(robot_pose[2]) + y_relative * np.cos(robot_pose[2])
    # add robot pose with delta target pose
    target_pose = {'y': (robot_pose[1]+delta_y_world)[0],
                   'x': (robot_pose[0]+delta_x_world)[0]}
    #print(f'delta_x_world: {delta_x_world}, delta_y_world: {delta_y_world}')
    #print(f'target_pose: {target_pose}')

    return target_pose


def merge_estimations(target_pose_dict, eps=0.15, min_samples=2):
    """
    function:
        merge estimations of the same target
    input:
        target_pose_dict: dict, generated by estimate_pose
    output:
        target_est: dict, target pose estimations after merging

    need to add outter bound of 2.7m
    """
    target_est = {}

    ######### Replace with your codes #########
    # TODO: replace it with a solution to merge the multiple occurrences of the same class type (e.g., by a distance threshold)
    # Convert dict to list of (class, x, y)
    target_est = {}

    # Convert dict to list of (class, x, y)
    detections = []
    for key, pose in target_pose_dict.items():
        target_type = key.split('_')[0]
        detections.append((target_type, pose['x'], pose['y']))

    # Process per class
    for target_type in set([d[0] for d in detections]):
        # Get detections for this class
        coords = np.array([[d[1], d[2]] for d in detections if d[0] == target_type])

        if len(coords) == 0:
            continue

        clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(coords)

        cluster_id = 0
        for cid in set(clustering.labels_):
            if cid == -1:  # noise
                continue
            cluster_points = coords[clustering.labels_ == cid]
            # Use mean (or median) as cluster centre
            x_mean, y_mean = cluster_points.mean(axis=0)
            target_est[f"{target_type}_{cluster_id}"] = {"x": float(x_mean),
                                                         "y": float(y_mean)}
            cluster_id += 1
    #########
   
    return target_est


# main loop
if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))     # get current script directory (TargetPoseEst.py)

    # read in camera matrix
    fileK = f'{script_dir}/calibration/param/intrinsic.txt'
    camera_matrix = np.loadtxt(fileK, delimiter=',')

    # init YOLO model
    model_path = f'{script_dir}/YOLO/model/yoloV11_10_V2.pt'
    yolo = Detector(model_path)

    # create a dictionary of all the saved images with their corresponding robot pose
    image_poses = {}
    with open(f'{script_dir}/lab_output/images.txt') as fp:
        for line in fp.readlines():
            pose_dict = ast.literal_eval(line)
            image_poses[pose_dict['imgfname']] = pose_dict['pose']

    # estimate pose of targets in each image
    target_pose_dict = {}
    detected_type_list = []
    for image_path in image_poses.keys():
        input_image = cv2.imread(image_path)
        bounding_boxes, bbox_img = yolo.detect_single_image(input_image)
        # cv2.imshow('bbox', bbox_img)
        # cv2.waitKey(0)
        robot_pose = image_poses[image_path]

        for detection in bounding_boxes:
            # count the occurrence of each target type
            occurrence = detected_type_list.count(detection[0])
            target_pose_dict[f'{detection[0]}_{occurrence}'] = estimate_pose(camera_matrix, detection, robot_pose)

            detected_type_list.append(detection[0])

    # merge the estimations of the targets so that there are at most 3 estimations of each target type
    target_est = {}
    target_est = merge_estimations(target_pose_dict, min_samples=3)
    print(target_est)
    # save target pose estimations
    with open(f'{script_dir}/lab_output/targets.txt', 'w') as fo:
        json.dump(target_est, fo, indent=4)

    print('Estimations saved!')

    # --------------------
    # Plot detections in arena (2.4m x 2.4m), AR=1
    # - Pre-clustering points: reduced opacity
    # - Post-clustering points: full opacity
    # - Colors per class from yolo.class_colour
    # --------------------
    try:
        fig, ax = plt.subplots(figsize=(6, 6))
        ax.set_xlim(-ARENA_BOUND, ARENA_BOUND)
        ax.set_ylim(-ARENA_BOUND, ARENA_BOUND)
        ax.set_aspect('equal', adjustable='box')  # ensure AR = 1
        ax.set_xlabel('x [m]')
        ax.set_ylabel('y [m]')
        ax.set_title('Fruit Positions: pre (transparent) vs post (solid) clustering')

        # Grid: small 0.3 m (minor), large 0.9 m (major)
        ax.xaxis.set_major_locator(MultipleLocator(1.0))
        ax.yaxis.set_major_locator(MultipleLocator(1.0))
        ax.xaxis.set_minor_locator(MultipleLocator(0.25))
        ax.yaxis.set_minor_locator(MultipleLocator(0.25))
        ax.grid(which='major', linestyle='-', linewidth=0.8, color='0.7')
        ax.grid(which='minor', linestyle=':', linewidth=0.5, color='0.85')

        # Helper to convert OpenCV BGR (0-255) to Matplotlib RGB (0-1)
        def bgr_to_rgb01(bgr):
            return (bgr[2] / 255.0, bgr[1] / 255.0, bgr[0] / 255.0)

        # Plot pre-clustering detections with reduced opacity
        pre_by_class = {}
        for key, pose in target_pose_dict.items():
            cls = key.split('_')[0]
            pre_by_class.setdefault(cls, []).append((pose['x'], pose['y']))

        for cls, pts in pre_by_class.items():
            color_rgb = bgr_to_rgb01(yolo.class_colour.get(cls, (128, 128, 128)))
            xs = [p[0] for p in pts]
            ys = [p[1] for p in pts]
            # Pre-cluster points: small size, transparent
            ax.scatter(xs, ys, c=[color_rgb], alpha=0.35, s=25, edgecolors='none')

        # Plot post-clustering estimations with full opacity
        post_by_class = {}
        for key, pose in target_est.items():
            cls = key.split('_')[0]
            post_by_class.setdefault(cls, []).append((pose['x'], pose['y']))

        for cls, pts in post_by_class.items():
            color_rgb = bgr_to_rgb01(yolo.class_colour.get(cls, (64, 64, 64)))
            xs = [p[0] for p in pts]
            ys = [p[1] for p in pts]
            # Post-cluster points: larger size, solid, thin edge
            ax.scatter(xs, ys, c=[color_rgb], alpha=1.0, s=50, edgecolors='black', linewidths=0.5)

        # Draw cluster outlines (convex hull per DBSCAN cluster of pre-cluster points)
        eps, min_samples = 0.15, 2  # keep in sync with merge_estimations defaults
        for cls, pts in pre_by_class.items():
            if len(pts) < 1:
                continue
            pts_np = np.array(pts, dtype=np.float32)
            labels = DBSCAN(eps=eps, min_samples=min_samples).fit(pts_np).labels_
            color_rgb = bgr_to_rgb01(yolo.class_colour.get(cls, (128, 128, 128)))

            for cid in np.unique(labels):
                if cid == -1:
                    continue  # skip noise
                cluster_pts = pts_np[labels == cid]
                if len(cluster_pts) < 3:
                    # Not enough points for a hull: emphasize with a ring marker
                    ax.scatter(cluster_pts[:, 0], cluster_pts[:, 1], s=80,
                               facecolors='none', edgecolors=color_rgb, linewidths=1.0)
                    continue
                hull = cv2.convexHull(cluster_pts.reshape(-1, 1, 2))
                hull = hull.squeeze()
                hx = np.r_[hull[:, 0], hull[0, 0]]
                hy = np.r_[hull[:, 1], hull[0, 1]]
                ax.plot(hx, hy, color=color_rgb, linewidth=1.2)
                ax.fill(hull[:, 0], hull[:, 1], color=color_rgb, alpha=0.10)

        plt.show()
    except Exception as e:
        print(f'Plotting failed: {e}')
